### PR TITLE
Hotfix/139 security updates briefings view dev master

### PR DESCRIPTION
**Pull request by cbrody**

### CODE REVIEW

**Comment by cbrody** [comment]
Just adding reviewers as heads-up that there are a lot of config changes in this PR due to update to Drupal v9.3. Existing branches based on dev-master will need to be re-based or merged.

**Comment by cbrody** [comment]
@finnlewis There's an error when running config-import against a fresh copy of the pubs production db 
```
Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
Content
The node.field_collection field needs to be updated.
```
On a quick inspection it looks like the Project content type is missing a reference to field_collection – could you look into this  please?

**Comment by cbrody** [comment]
@finnlewis I ran it again with a fresh db copy and had the same issue.

**Comment by finnlewis** [comment]
Hi @cbrody 

On a fresh copy of the pubs database, on dev-master, I get a different error on the first import. Then the second import runs through OK. 

```
 [notice] Finalizing configuration synchronization.
 [error]  Drupal\Core\Config\ConfigException: Errors occurred during import in Drush\Drupal\Commands\config\ConfigImportCommands->doImport() (line 346 of /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php). 

In ConfigImportCommands.php line 360:
                                                                                                                                                                                           
  The import failed due to the following reasons:                                                                                                                                          
  Unexpected error during import with operation delete for field.field.node.project.field_collection: Attempt to create a field field_collection that does not exist on entity type node.  
                                                                                                                                                                                           

:~/sites/l.iied/gitroot$ lando drush cim
+------------+-------------------------------------------------------+-----------+
| Collection | Config                                                | Operation |
+------------+-------------------------------------------------------+-----------+
|            | core.entity_form_display.media.document.media_library | Update    |
|            | core.entity_form_display.media.video.default          | Update    |
|            | core.entity_form_display.media.image.default          | Update    |
|            | core.entity_form_display.media.audio.default          | Update    |
|            | core.entity_view_display.taxonomy_term.tags.default   | Update    |
|            | core.entity_form_display.node.project.default         | Update    |
|            | core.entity_view_display.node.project.teaser          | Update    |
|            | core.entity_view_display.node.project.search_result   | Update    |
|            | core.entity_view_display.node.project.rss             | Update    |
|            | core.entity_view_display.node.project.full            | Update    |
|            | core.entity_view_display.node.project.default         | Update    |
|            | core.entity_view_display.node.project.card            | Update    |
|            | core.entity_form_display.user.user.default            | Update    |
|            | views.view.manage_lists                               | Update    |
|            | field.field.node.project.field_collection             | Delete    |
+------------+-------------------------------------------------------+-----------+

 Import the listed configuration changes? (yes/no) [yes]:
 > 

 [notice] Synchronized configuration: delete field.field.node.project.field_collection.
 [notice] Synchronized configuration: update core.entity_form_display.media.document.media_library.
 [notice] Synchronized configuration: update core.entity_form_display.media.video.default.
 [notice] Synchronized configuration: update core.entity_form_display.media.image.default.
 [notice] Synchronized configuration: update core.entity_form_display.media.audio.default.
 [notice] Synchronized configuration: update core.entity_view_display.taxonomy_term.tags.default.
 [notice] Synchronized configuration: update core.entity_form_display.node.project.default.
 [notice] Synchronized configuration: update core.entity_view_display.node.project.teaser.
 [notice] Synchronized configuration: update core.entity_view_display.node.project.search_result.
 [notice] Synchronized configuration: update core.entity_view_display.node.project.rss.
 [notice] Synchronized configuration: update core.entity_view_display.node.project.full.
 [notice] Synchronized configuration: update core.entity_view_display.node.project.default.
 [notice] Synchronized configuration: update core.entity_view_display.node.project.card.
 [notice] Synchronized configuration: update core.entity_form_display.user.user.default.
 [notice] Synchronized configuration: update views.view.manage_lists.
 [notice] Finalizing configuration synchronization.
 [success] The configuration was imported successfully.
:~/sites/l.iied/gitroot$ lando drush cim
```

**Comment by cbrody** [comment]
@finnlewis Thanks for that . Sorry I wasn't clear: the error I'm seeing is on the /admin/reports/status page - the config import runs fine the second time.

**Comment by finnlewis** [comment]
Oh, sorry, maybe you're on the  hotfix/139-security-updates-briefings-view-dev-master branch.

I'll test that branch now.

**Comment by finnlewis** [comment]
> @finnlewis Thanks for that . Sorry I wasn't clear: the error I'm seeing is on the /admin/reports/status page - the config import runs fine the second time.

Ah OK. I'll take a look there!

**Comment by finnlewis** [comment]
@cbrody looks like the schema is out of whack in some way, as we are essentially trying to change the field type on field_collection from a text field to an entity reference. 

The quickest and safest way might be to name the field something different, so that it is deleting one field and creating a new one. Then update the migrations to use the new field.

If so, perhaps we call the new field 'field_collections' or 'field_collect' to maintain the meaning in the machine name.

It used to be that we could use drush entity:updates to resolve field configuration / schema changes, but this was removed as it sometimes caused more problems than it solved: https://www.drupal.org/node/3034742. While there is a contributed replacement https://www.drupal.org/project/devel_entity_updates it is not recommended for production deployment situations as it might have unintended side effects.

There are example hook_update_N implementations on https://www.drupal.org/node/3034742 which could help us set the schema straight as part of drush updb, so I'm happy to explore that if we want to keep the machine name as is.

If renaming the field is acceptable, probably quickest and safest.

**Comment by cbrody** [comment]
I agree that renaming the field is probably the safest & quickest solution. Would you like to commit the necessary changes to this branch or shall I merge as is?

**Comment by finnlewis** [comment]
Hey @cbrody 

I've been having a problem with the config on this branch, running config-import and getting the same config changes wanting to import every time: 

```

finn@finnibuntu:~/sites/l.iied/gitroot$ lando drush cim
+------------+-------------------------------------------------------+-----------+
| Collection | Config                                                | Operation |
+------------+-------------------------------------------------------+-----------+
|            | filter.format.basic_html                              | Update    |
|            | core.entity_form_display.media.document.media_library | Update    |
|            | core.entity_form_display.media.video.default          | Update    |
|            | core.entity_form_display.media.image.default          | Update    |
|            | core.entity_form_display.media.audio.default          | Update    |
|            | core.entity_view_display.taxonomy_term.tags.default   | Update    |
|            | core.entity_form_display.user.user.default            | Update    |
|            | views.view.comments_recent                            | Update    |
+------------+-------------------------------------------------------+-----------+

 Import the listed configuration changes? (yes/no) [yes]:
 > 

 [notice] Synchronized configuration: update filter.format.basic_html.
 [notice] Synchronized configuration: update core.entity_form_display.media.document.media_library.
 [notice] Synchronized configuration: update core.entity_form_display.media.video.default.
 [notice] Synchronized configuration: update core.entity_form_display.media.image.default.
 [notice] Synchronized configuration: update core.entity_form_display.media.audio.default.
 [notice] Synchronized configuration: update core.entity_view_display.taxonomy_term.tags.default.
 [notice] Synchronized configuration: update core.entity_form_display.user.user.default.
 [notice] Synchronized configuration: update views.view.comments_recent.
 [notice] Finalizing configuration synchronization.
 [success] The configuration was imported successfully.

```

Then run it again and I get the same thing.

I think I will make the changes to the field_collection on another branch off dev-master and deal with that first, then merge on into this branch if that works.

**Pull request closed without merging**
