### PR TITLE
Feature/134 migrate general

### PR DESCRIPTION
**Pull request by finnlewis**
Hi @cbrody !

This pull represents work to date on the Drupal 7 migrations. 

We can break it up into smaller pull requests if that helps with review. 

For example: 

- https://github.com/IIED-org/pubs/compare/dev-master...feature/132-migrate-translations
- https://github.com/IIED-org/pubs/compare/dev-master...feature/133-migrate-news

Happy to talk it through when needed or take feedback from any testing you do.

### CODE REVIEW

**Comment by finnlewis** [comment]
- [ ] What is 44 config/default/core.entity_form_display.taxonomy_term.person.dashboard_add_author.yml ?

**Comment by finnlewis** [comment]
@cbrody 

1. Jumbotron looks to be a custom block type: https://iied-main.lndo.site/admin/structure/block/block-content/manage/jumbotron 
2. The author [person] vocabulary has an existing display mode of 'dashboard_add_author' https://iied-main.lndo.site/admin/structure/taxonomy/manage/person/overview/form-display/dashboard_add_author

**Comment by finnlewis** [comment]
The field_theme on the person taxonomy is a field on a taxonomy entity, so it is not possible to use the same field_theme_s_ from the node fields. If you think it is important, we could re-create the taxonomy field_theme field as field_theme_s_ - but I can't see a reason to do so.

**Comment by finnlewis** [comment]
Fixed the field_video migration with the latest commit.

Using this as a migration example: https://www.iied.org/development-climate-days-cop17

I now have the correct video media entity in the destination node: 

image

**Comment by finnlewis** [comment]
Hi @cbrody 

I've reviewed and addressed the issues we discussed above. 

Passing this to you now to review and confirm the translation requirements for content types and fields other than projects. 

Once we know, I can 

- [ ] adjust the configuration to ensure fields and content is translatable where it should be and
- [ ] add migrations for any other content types that have source translations to migrate.

Let me know if there is anything else you need me to look at in the mean time.

**Comment by cbrody** [comment]
Hi @finnlewis, thanks for the update. Re the configuration of translatable fields, we may leave this until after migration as it's not highly urgent. Re translations for other content types @ncktrnr is doing an audit of these.

**Comment by cbrody** [comment]
Re the user > person migration, can we move the three Boolean fields into a single multi-select field, as per row 34 of the spreadsheet: https://docs.google.com/spreadsheets/d/1OuUOnnKoVaOM3e7TNmnXGeWk9JUL3cMFEk9V-wsrQe0/edit#gid=746514639

**Comment by finnlewis** [comment]
Discussing with @cbrody now, we will migrate the boolean fields into a new taxonomy field 'Person type' [field_person_type], referencing a person_type taxonomy with initial terms: Staff, Guest, Former staff

@ncktrnr - does that sound about right?

**Comment by ncktrnr** [comment]
> Discussing with @cbrody now, we will migrate the boolean fields into a new taxonomy field 'Person type' [field_person_type], referencing a person_type taxonomy with initial terms: Staff, Guest, Former staff
> 
> @ncktrnr - does that sound about right?

Yes, that sounds right to me. Thanks

**Comment by finnlewis** [comment]
Hi @cbrody 

I've updated the person taxonomy fields with new person_type term reference to combine the three former boolean fields into a single field, and updated the migration to create the new terms on the fly. 

After an update migration with 

```
lando drush mim iied_d7_terms_person --update
```

We now have three terms in the taconomy:

image

and people get the appropriate terms: 

image

image

**Comment by finnlewis** [comment]
Following comments and discussion this week, I'll go ahead and merge this now so we can progress with other issues by branching off dev-master.

**Pull request merged**
