### PR TITLE
Merge latest hotfix into dev-master

### PR DESCRIPTION
**Pull request by cbrody**

### CODE REVIEW

**Comment by cbrody** [comment]
Hi @finnlewis can you advise on how best to resolve these conflicts - thanks!

**Comment by finnlewis** [comment]
Hi @cbrody 

Just to confirm our discussion earlier, I will take a look this evening and assess.

**Comment by finnlewis** [comment]
Hi @cbrody 

Looking at the conflicts and thinking this over, I wonder if we should allow the configuration on dev-master and master to diverge at this point. 

We have made significant changes to content types and fields on the dev-master branch that we want to keep and deploy along with the migration in due course. We are also making small changes like the encoding of imagemagick.settings.yml. So we could just accept that the configuration is diverging and not try to merge configuration changes back from master. 

We could then maybe try to cherry-pick the commits that changed the codebase 
https://github.com/IIED-org/pubs/pull/143/commits/f49cba51af3839a2741bb5aecaaf6981565ab1c7
and
https://github.com/IIED-org/pubs/pull/143/commits/452424177cc40bb78241a97887aae9ebf7236c76

Alternatively we can run the composer updates on the dev-master branch as new commits, allowing the branches to completely diverge. This would then mean we would be replacing the master branch with dev-master at the point of release, rather than attempting to merge dev-master back into master. 

I guess the latter is probably cleaner and safer, unless there are other commits on the master branch that we do want to merge back to dev-master.

What do you think?

**Comment by cbrody** [comment]
Thanks @finnlewis, that's really helpful. We'll discuss and review the options.

**Pull request closed without merging**
