### PR TITLE
Add image path rewrite for /files/filename.ext to /sites/default/file…

### PR DESCRIPTION
**Pull request by finnlewis**
…s/filename.ext to reqrite styles plugin

https://github.com/IIED-org/pubs/issues/205

### CODE REVIEW

**Comment by cbrody** [comment]
Just to check that this will only match file paths that actually begin with `/files/` and not paths that have `/files/` as a substring (e.g. `/sites/default/files/` ?

**Comment by finnlewis** [comment]
Good question. I will find a node to test that on!

**Comment by cbrody** [comment]
Perhaps the regex needs to be `'/src="\/files\/(.*?.(?:png|jpeg|jpg|gif|bmp|pdf))/';`

**Comment by finnlewis** [comment]
I think you are right.... this is potentially matching sites/default/files for local and for links to remotes too. 

I will need to do more work on this this afternoon.

**Comment by finnlewis** [comment]
@cbrody see https://github.com/IIED-org/pubs/pull/327

**Pull request merged**
